---

# debops.unattended_upgrades
unattended_upgrades__release_origins:

  'default':
    - "o=Debian,a={{ ansible_distribution_release }}"
    - "o=Debian,a={{ ansible_distribution_release + '-updates' }}"
    - "o=Syncthing"

# debops.apt
apt__original_sources: []

apt_preferences__list:
  - package: '*'
    pin: 'release stretch-backports'
    priority: '70'
    filename: "stretch-backports"
  - package: '*'
    pin: 'release sid'
    priority: '50'
    filename: "sid"
  - package: '*'
    pin: 'release unstable'
    priority: '50'
    filename: "unstable"
  - package: '*'
    pin: 'release testing'
    priority: '60'
    filename: "testing"
  - package: '*'
    pin: 'release experimental'
    priority: '40'
    filename: "experimental"

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
