---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'docker-engine'
    - 'python-setuptools'

- name: update pip
  easy_install:
    name: pip

- name: install docker-compose
  pip:
    name: docker-compose

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
