---
# ansible
ansible_user: root

console_locales: [ 'en_US.UTF-8' ]
console_locales_default: 'en_US.UTF-8'
console_root_password: "{{ lookup('file', secret + '/users/root/password_home') }}"
core__packages:
  - 'mc'
  - 'htop'
  - 'iotop'
  - 'sysstat'
  - 'screen'
  - 'vim'
  - 'nload'
  - 'aptitude'
  - 'tasksel'
  - 'p7zip'
  - 'lsof'
  - 'iftop'
  - 'dstat'
  - 'ed'
  - 'python'
  - 'python-apt'
  - 'lsb-release'
  - 'make'
  - 'sudo'
  - 'git'
  - 'wget'
  - 'curl'
  - 'rsync'
  - 'bridge-utils'
  - 'openssh-server'
  - 'bsdutils'
  - 'python-pycurl'
  - 'python-httplib2'
  - 'apt-transport-https'
  - 'acl'
  - 'python-pip'
  - 'ca-certificates'

#debobs.auth
auth_ldap_conf: False
auth_admin_accounts: [ 'ansicon' ]

#debobs.users
users_default:
  - '{{ users_ansicon }}'

users_ansicon:
  - name:   'ansicon'
    state:  'present'
    group:  'ansicon'
    groups: ['admins']
    shell: '/bin/bash'
    sshkeys:
      - "{{ lookup('file', secret + '/users/ansicon/sshkeys') }}"

users_le9i0nx:
  - name:   'le9i0nx'
    state:  'present'
    group:  'le9i0nx'
    groups: ['sudo','sshusers']
    shell: '/bin/bash'
    update_password: 'always'
    password: "{{ lookup('file', secret + '/users/le9i0nx/password') }}"
    sshkeys:
      - "{{ lookup('file', secret + '/users/le9i0nx/sshkeys') }}"

users_root:
  - name:   'root'
    state:  'present'
    group:  'root'
    password: "{{ lookup('file', secret + '/users/root/password_home') }}"
    sshkeys:
      - "{{ lookup('file', secret + '/users/root/sshkeys') }}"
      - "{{ lookup('file', secret + '/users/root/sshkeys2') }}"

users_admins:
  - '{{ users_ansicon }}'
#  - '{{ users_root }}'
  - '{{ users_le9i0nx }}'

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
